import 'package:hive/hive.dart';

part 'shopping_item.g.dart'; // This is generated by Hive's build_runner

@HiveType(typeId: 0)
class ShoppingItem extends HiveObject {
  @HiveField(0)
  String name;

  @HiveField(1)
  int quantity;

  @HiveField(2)
  double price;

  @HiveField(3)
  String category;

  @HiveField(4)
  bool isChecked;

  ShoppingItem({
    required this.name,
    required this.quantity,
    required this.price,
    required this.category,
    this.isChecked = false,
  });
}
